kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: nextflow-cluster    # you can choose this name freely
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/ls/CLionProjects/do_stuff/nextflow/
        containerPath: /host-data
  - role: worker
    extraMounts:
      - hostPath: /home/ls/CLionProjects/do_stuff/nextflow/
        containerPath: /host-data
  - role: worker
    extraMounts:
      - hostPath: /home/ls/CLionProjects/do_stuff/nextflow/
        containerPath: /host-data