apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi    # example value
  hostPath:
    path: /host-data   # the path used in the kind-config.yaml

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-host-data
spec:
  volumeName: pv-host-data      # must be the name of the volume above
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    # example value